version: "3"
services:
  meta1:
    container_name: meta1
    hostname: meta1
    stdin_open: true
    tty: true
    build: .
    image: metadium/multinode-demo:latest
    volumes:
      - ".:/opt"
    entrypoint: ["/usr/local/metadium/bin/gmet-demo.sh", "start-leader", "meta1", "meta2", "meta3"]
  meta2:
    container_name: meta2
    hostname: meta2
    stdin_open: true
    tty: true
    image: metadium/multinode-demo:latest
    depends_on:
      - meta1
    volumes:
      - ".:/opt"
    entrypoint: ["/usr/local/metadium/bin/gmet-demo.sh", "start"]
  meta3:
    container_name: meta3
    hostname: meta3
    stdin_open: true
    tty: true
    image: metadium/multinode-demo:latest
    depends_on:
      - meta1
    volumes:
      - ".:/opt"
    entrypoint: ["/usr/local/metadium/bin/gmet-demo.sh", "start"]
